require_relative './zrankings/version'
require_relative './zrankings/scraper'
require_relative './zrankings/resort'
require_relative './zrankings/cli'
require 'nokogiri'
require 'open-uri'
require 'colorize'